- Runtime/codebase/data/MetaplexData.cs
| Ready|Bug|No | [Link](https://github.com/garbles-labs/Solana.Unity-SDK/issues/28) |
_What problem are you trying to solve?_
When parsing nft data the animation url was missingg
_How did you solve the problem?_
Added the field to the metaplex json data.
> 🐛 Add animation url to metaplex data

- Runtime/Plugins/Phantom.jslib
- Runtime/codebase/IWalletBase.cs
- Runtime/codebase/InGameWallet.cs
- Runtime/codebase/PhantomWallet.cs
- Runtime/codebase/PhantomWallet/PhantomDeepLink.cs
- Runtime/codebase/PhantomWallet/PhantomMessagePayload.cs
- Runtime/codebase/PhantomWallet/PhantomMessagePayload.meta
- Runtime/codebase/PhantomWallet/PhantomWebGL.cs
- Runtime/codebase/PhantomWallet/Utils.cs
- Runtime/codebase/WalletBase.cs
- Runtime/codebase/Web3AuthWallet.cs
- Runtime/codebase/XNFTWallet.cs
Phantom signMessage method support
We didn't have a method for requesting a message signature from a Phantom wallet. We need it to implement Phantom wallet authentication.
[https://docs.phantom.app/solana/integrating-phantom/deeplinks-ios-and-android/provider-methods/signmessage](url)
[https://docs.phantom.app/solana/integrating-phantom/extension-and-in-app-browser-web-apps/signing-a-message](url)
Implemented signMessage method using deeplinks (for mobile) and javascript provider methods (for WebGL).
> Add support for Phantom signMessage method

- Runtime/codebase/PhantomWallet/PhantomWebGL.cs
- Runtime/codebase/WalletBase.cs
| Ready | Bug | No | #49  |
See #49 
Equals works differently on WebGL, replaced with SequenceEqual for deduplicating correctly empty, removing the empty signature.
Closes #49
> :bug: Fix WebGL signature

- Samples~/Solana Wallet/Scripts/example/simple_screen_manager/utility/TokenItem.cs
Bug: When loading NFTs in the example the webgl version would freeze. 
Solution: There was a token amount parsed into an int but the amount can be bigger than int.
> Fix overflow error in token item

- Runtime/codebase/InGameWallet.cs
- Runtime/codebase/WalletBase.cs
- Runtime/codebase/Web3.cs
| Ready | Feature  |  No | - |
Previously it was only possible to restore a wallet from mnemonics
Added more restore options, available methods include:
- Mnemonics words
- Bip39 private key 
- Secret byte array
> :sparkles: Add more wallet restore options

- Runtime/codebase/SolanaMobileWalletAdapter.cs
> ⚠️ NOTE: Use notes like this to emphasize something important about the PR.
>  
>  This could include other PRs this PR is built on top of; API breaking changes; reasons for why the PR is on hold; or anything else you would like to draw attention to.
| Ready | Feature | No | - |
As reported on Discord from `BlackDemonZyT`
```
Hello there, im having a problem, im using this line of code to let user link their mobile wallets:
WalletBase wallet = new SolanaMobileWalletAdapter(new SolanaMobileWalletAdapterOptions(), RpcCluster.MainNet, null, null, true);
But every time i do that line of code, the phantom wallet opens asking to accept linking, why, the user already accepted it, shouldnt this line of code just …
```
> :sparkles: Add option to keep sms connection alive

- Runtime/Plugins/xNFT.jslib
- Runtime/codebase/XNFTWallet.cs
> ⚠️ NOTE: Use notes like this to emphasize something important about the PR.
>  
>  This could include other PRs this PR is built on top of; API breaking changes; reasons for why the PR is on hold; or anything else you would like to draw attention to.
| Ready | Feature | No | #85  |
Sign Message implementation did not exist for XNFT Wallet Adapter.
Added implementation inside XNFT.jslib and XNFTWallet.cs files.
> ✨ Add message sign to xNFT wallet adapter.

- Runtime/codebase/Web3.cs
- Runtime/codebase/nft/Nft.cs
- Runtime/codebase/utility/FileDownloader.cs
| Ready| Enhance/Bug | No | -|
- Nfts loading failing with most RPCs due to rate limit
- Due to a bug in Unity, Destroy was triggering an exception if exiting from play mode while the NFTs are still loading
- Unused LoadJson method
- sNFT were not displayed due to the check on amount == 1
- Add a parameter to add a delay between calls (This is a temporary solution and will be superseded by #120 )
- Add a Destroy with uses DestroyImmediate if the game is not running
- Remove unused methods
- Remove amount == 1 check
> :sparkles: Enhance NFT loading

- Runtime/Plugins/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.jslib
> ⚠️ NOTE: Use notes like this to emphasize something important about the PR.
>  
>  This could include other PRs this PR is built on top of; API breaking changes; reasons for why the PR is on hold; or anything else you would like to draw attention to.
| Ready| Hotfix | No | [Link](#119 ) |
xNFT Sign Message never return anything.
xNFT Sign Message returns byte array already, so we just needed to convert it to base64, but not like you fixed it, it still did not work.
Instead of using signedMessage.toString('base64'); I've changed it to btoa(String.fromCharCode(...signedMessage));
Now I've tested it and it works as intended.
> Fix xNFT sign message issue.

- Runtime/codebase/IWalletBase.cs
- Runtime/codebase/SessionWallet.cs
- Runtime/codebase/WalletBase.cs
| Status  | Type  | ⚠️ Core Change | 
| Ready|Bug|No | 
_What problem are you trying to solve?_
Session wallet would not handle expired session and refunds where not working. 
_How did you solve the problem?_
- First problem was that refund was getting a confirmed block hash but was sending with finalzed blockhash. This led the transaction to fail so the players never got their sol back. Fixed by changing send transaction default to confirmed
- Somtimes the refund transaction would fail, since GetBalance would get the finalized balance which let to it being out of date, so the calulation was wrong. Also added a buffer of 5000 lamports in case there is another transaction still running during the confirmation
- Session wallet would return a null account in …
> Fix session refund and account being null when session isn't valid

- Runtime/Plugins/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.jslib
- Runtime/codebase/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.cs
| Ready | Feature/Bug | No | - |
WebGL Wallet Adapter is not returning anything when the user reject to sign a message/transaction
Handle rejection and propagate the exception
> :bug: Handle rejection in WebGL wallet adapter

- Runtime/codebase/UnityRateLimiter.cs
- Runtime/codebase/UnityRateLimiter.cs.meta
- Runtime/codebase/WalletBase.cs
- Runtime/codebase/Web3.cs
Implement a configurable Rate Limiter which can be used to support all 
| Ready | Feature  | No |  |
Free and low tier Rpc providers have a rate limit that could be hit easily
Allow to rate limit requests
> :sparkles: Add rate limiter

- Runtime/codebase/SessionWallet.cs
| Ready | Feature/Refactor | No | - |
SessionWallet was defaulting to devnet and requiring several unnecessary configuration
- SessionWallet is now instantiated with an external wallet, RPC, Websockets and cluster configuration are copied from it.
- The external wallet is used as the authority for the session wallet
> :zap: Improve Session Wallet

- Runtime/codebase/SessionWallet.cs
| Ready | Feature/Bug | No | - |
As discussed wtih @Woody4618 :
- Throwing exceptions on bool returning methods
- Checked for null accounts rather than throwing exception on bool returning methods
> :bug: Improve Session Wallet errors handling

- Runtime/codebase/Web3AuthWallet.cs
| Ready | Feature | No | - |
Web3Auth UserInfo were not exposed after the login 
Added a public userInfo field that can be accessed after the login:
As a simple example, a script can register to the OnLogin event and print the user email, if available.
```csharp
public void Start()
{
Web3.OnLogin += OnLogin;
}
private void OnLogin(Account obj)
{
if(Web3.Wallet is Web3AuthWallet) Debug.Log(((Web3AuthWallet)Web3.Wallet).userInfo?.email);
}
```
> :sparkles: Expose Web3Auth user info

- Runtime/codebase/PhantomWallet.cs
- Runtime/codebase/PhantomWallet/PhantomDeepLink.cs
| Ready | Feature | No | - |
Phantom Deeplink wallet implementation (used on iOS) was requiring to login at each app interaction.
- Add a deterministic psw derivation to save the phantom session_id and the channel encryption keypair
- Save and load session information automatically on login
> :sparkles: Keep connection active with Phantom deeplink wallet

- Runtime/Plugins/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.jslib
- Runtime/codebase/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.cs
| Ready| Feature | No | #200  |
Include Solana Mobile Wallet Adapter for WebGL builds when running in mobile.
Most of the code containing the solution is in the [unity-js-wallet-adapter](https://github.com/magicblock-labs/unity-js-wallet-adapter) where SolanaMobileWallet adapter instance is created when running in mobile. For that, we needed to pass the RPC cluser selected to the JS runtime. We just do that here, by setting a global variable  window.rpcCluster with the cluster name from Unity thorugh jslib.
It's important to note that this PR alone does not provide the solution, it has a strict dependency on the [PR for unity-js-wallet-adapter]( https://github.com/magicblock-labs/unity-js-wallet-adapter/pull/6)
> Set rpc cluster name as global window variable for walletAdapterLib

- Runtime/Plugins/Web3AuthSDK/Types/AES256CBC.cs
- Runtime/Plugins/Web3AuthSDK/Types/LoginParams.cs
- Runtime/Plugins/Web3AuthSDK/Types/Web3AuthOptions.cs
- Runtime/Plugins/Web3AuthSDK/Types/Web3AuthResponse.cs
- Runtime/Plugins/Web3AuthSDK/Web3Auth.cs
| Ready | Feature | No | - |
Update Web3auth SDK to v2.1.1: https://github.com/Web3Auth/web3auth-unity-sdk/releases/tag/2.1.1
> :sparkles: Update Web3Auth SDK to v2.1.1

- Runtime/Plugins/NativeWebSocket/NativeWebSocket.jslib
- Runtime/Plugins/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.jslib
- Runtime/Plugins/WebGLSupport/WebGLInput/WebGLInput.jslib
- Runtime/Plugins/WebGLSupport/WebGLWindow/WebGLWindow.jslib
- Runtime/codebase/SolanaWalletAdapterWebGL/SolanaWalletAdapterWebGL.cs
| Ready|Hotfix | No | [Link](https://github.com/magicblock-labs/Solana.Unity-SDK/issues/233) |
In the WebGL build of Unity 2023 and above, when enabling the "Target WebAssembly 2023" option in Player Settings > Publishing Settings, the game freezes after the initial loading.
According to the Unity documentation at the link below:
https://docs.unity3d.com/6000.0/Documentation/Manual/web-interacting-browser-deprecated.html#dyncall
the dynCall() function has been deprecated and should be replaced with makeDynCall().
Please note that this change is backward-compatible, and there will be no issues even if the "Target WebAssembly 2023" option is not enabled.
As a result, I replaced this deprecated function with the …
> Update deprecated code inside jslib plugins

- Runtime/Plugins/Web3AuthSDK/Types/SecurePlayerPrefs.cs
> ⚠️ NOTE: Use notes like this to emphasize something important about the PR.
>  
>  This could include other PRs this PR is built on top of; API breaking changes; reasons for why the PR is on hold; or anything else you would like to draw attention to.
| Ready/Hold | Feature/Bug/Tooling/Refactor/Hotfix | Yes/No | [Link](<Issue link here>) |
There is  some typos in comment.
Fix some typos in comment
_Insert screenshots of example code output_
**BEFORE**:
[insert screenshot here]
**AFTER**:
[insert screenshot here]
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
**New scripts**:
- `script` : script details
**New dependencies**:
- `dependency` : …
> chore: fix some typos in comment
